version: "2"
services:
    app:
        container_name: app
        restart: always
        image: lucienkerl/sssh-backend
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        restart: always
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"